### ISSUE TITLE
MongoDB port to be changed to non-standard port.

### ISSUE THREAD

**Issue by binoopnanu** [eliasgranderubio/dagda#38]
### Short description
I was trying to deploy the dokcer-compose option on our environment, unfortunately I cant use the normal mongodb port 27017 as its in use already.. So for example I am using a host port 27018 and container port 27017. 

Would it work ? We tried with some options without much luck.  Please advice.

**Comment by eliasgranderubio** [comment]
Hi @binoopnanu ,

Probably, your docker environment has the `icc=false` configuration parameter setted, so your containers cannot communicate with others within the same host through docker bridge networks.

Despite of this, you can configure your `docker-compose.yml` like I show you below thanks to the unresolved issue 21990 of the Moby repository --> https://github.com/moby/moby/issues/21990

Please, test the next `docker-compose.yml` in your environment and let me know if your issue would be fixed :-)
```
version: '2'
services:
  dagda:
    build: .
    image: 3grander/dagda:0.8.0
    container_name: dagda
    entrypoint: python dagda.py start -s 0.0.0.0 -p 5000 -m 172.17.0.1 -mp 27018
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    depends_on:
      - vulndb
  vulndb:
    image: mongo
    container_name: vulndb
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db

```
